stages:
  - build
  - test

build-java-project:
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - /home/gitlab-runner/
  
run_tests:
  stage: test
  image: gradle:7.5-jdk17
  script:
    - ./gradlew test